# name: test1
# on: [push]
# jobs:
#   job1:
#    runs-on: ubuntu-latest
#    steps:
#     - name: Run Test0
#       run: |
#        output=$(node dist/Test1.js)
#        exit_code=$output
#        if [ $exit_code -ne 0 ]; then
#        echo "Error: The Node.js script failed with exit code $exit_code" exit 1 # Exit the workflow with an error code
#        fi

name: test2

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.19.0"

      - name: Run Test1
        run: node src/Test1.js
